var me=null, patients=[], services=[];
function $(s){return document.querySelector(s)}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
async function api(url,opt){opt=opt||{};opt.headers=Object.assign({'Content-Type':'application/json'},opt.headers||{});var r=await fetch(url,opt),d=await r.json().catch(function(){return {error:'Invalid server response'}});if(!r.ok)throw Error(d.error||'Request failed');return d}
function toast(msg,bad){var t=$('#toast');t.textContent=msg;t.className=bad?'bad show':'show';setTimeout(function(){t.className=''},2500)}
function shell(title,button){return '<div class="head"><div><h2>'+title+'</h2><p class="muted">Barangay Health Center Management System</p></div>'+(button||'')+'</div>'}
function modal(title,html,save){var m=$('#modal');m.className='modal';m.innerHTML='<div class="modal-box"><h2>'+title+'</h2>'+html+'</div>';m.querySelector('form').addEventListener('submit',async function(e){e.preventDefault();try{await save(new FormData(e.target));closeModal()}catch(x){toast(x.message,true)}})}
function closeModal(){$('#modal').className='hidden';$('#modal').innerHTML=''}
function formData(f){var o={};f.forEach(function(v,k){o[k]=v});return o}
async function dashboard(){var d=(await api('/api/dashboard')).data;$('#main').innerHTML=shell('Dashboard')+'<div class="cards"><div class="card">Patients<div class="metric">'+d.patients+'</div></div><div class="card">Appointments<div class="metric">'+d.appointments+'</div></div><div class="card">Medical Records<div class="metric">'+d.medicalRecords+'</div></div><div class="card">Health Services<div class="metric">'+d.services+'</div></div><div class="card">Today Scheduled<div class="metric">'+d.todayAppointments+'</div></div></div><div class="panel"><h3>System ready</h3><p class="muted">All records are stored in MySQL. Use the navigation to manage residents, appointments, records, services and users.</p></div>'}
async function patientsPage(){patients=(await api('/api/patients')).data;var rows=patients.map(function(p){return '<tr><td>'+p.id+'</td><td>'+esc(p.firstName)+' '+esc(p.lastName)+'</td><td>'+p.dateOfBirth+'</td><td>'+p.gender+'</td><td>'+esc(p.contactNumber)+'</td><td>'+esc(p.address)+'</td><td class="actions"><button class="secondary" onclick="editPatient('+p.id+')">Edit</button>'+(me.role==='Administrator'?'<button class="danger" onclick="delPatient('+p.id+')">Delete</button>':'')+'</td></tr>'}).join('');$('#main').innerHTML=shell('Patients','<button class="primary" onclick="patientModal()">+ Add Patient</button>')+'<div class="panel"><table><thead><tr><th>ID</th><th>Name</th><th>DOB</th><th>Gender</th><th>Contact</th><th>Address</th><th>Actions</th></tr></thead><tbody>'+(rows||'<tr><td colspan="7" class="empty">No patients found.</td></tr>')+'</tbody></table></div>'}
function patientModal(p){p=p||{};modal(p.id?'Edit Patient':'Add Patient','<form><div class="grid"><label>First name<input name="firstName" maxlength="50" required value="'+esc(p.firstName)+'"></label><label>Last name<input name="lastName" maxlength="50" required value="'+esc(p.lastName)+'"></label><label>Date of birth<input name="dateOfBirth" type="date" required value="'+(p.dateOfBirth||'')+'"></label><label>Gender<select name="gender"><option '+(p.gender==='Male'?'selected':'')+'>Male</option><option '+(p.gender==='Female'?'selected':'')+'>Female</option><option '+(p.gender==='Other'?'selected':'')+'>Other</option></select></label><label>Contact number<input name="contactNumber" maxlength="11" required value="'+esc(p.contactNumber)+'"></label><label>Address<input name="address" maxlength="200" required value="'+esc(p.address)+'"></label></div><div class="modal-actions"><button type="button" class="light" onclick="closeModal()">Cancel</button><button class="primary">Save</button></div></form>',async function(f){await api(p.id?'/api/patients/'+p.id:'/api/patients',{method:p.id?'PUT':'POST',body:JSON.stringify(formData(f))});toast('Patient saved');patientsPage()})}
async function editPatient(id){patientModal(patients.find(function(x){return x.id===id}))}
async function delPatient(id){if(confirm('Delete patient and related records?')){await api('/api/patients/'+id,{method:'DELETE'});toast('Patient deleted');patientsPage()}}
async function appointmentsPage(){var a=(await api('/api/appointments')).data;patients=(await api('/api/patients')).data;var rows=a.map(function(x){return '<tr><td>'+x.appointmentDate+'</td><td>'+x.appointmentTime+'</td><td>'+esc(x.patientName)+'</td><td>'+esc(x.service)+'</td><td><span class="status">'+x.status+'</span></td><td><button class="danger" onclick="delAppointment('+x.id+')">Delete</button></td></tr>'}).join('');$('#main').innerHTML=shell('Appointments','<button class="primary" onclick="appointmentModal()">+ Add Appointment</button>')+'<div class="panel"><table><thead><tr><th>Date</th><th>Time</th><th>Patient</th><th>Service</th><th>Status</th><th>Action</th></tr></thead><tbody>'+(rows||'<tr><td colspan="6" class="empty">No appointments found.</td></tr>')+'</tbody></table></div>'}
function appointmentModal(){modal('Add Appointment','<form><div class="grid"><label>Patient<select name="patientId" required>'+patients.map(function(p){return '<option value="'+p.id+'">'+esc(p.firstName+' '+p.lastName)+'</option>'}).join('')+'</select></label><label>Service<input name="service" list="serviceList" required><datalist id="serviceList">'+services.map(function(s){return '<option value="'+esc(s.name)+'">' }).join('')+'</datalist></label><label>Date<input name="appointmentDate" type="date" required></label><label>Time<input name="appointmentTime" type="time" required></label><label>Status<select name="status"><option>Scheduled</option><option>Completed</option><option>Cancelled</option></select></label><label class="full">Notes<textarea name="notes"></textarea></label></div><div class="modal-actions"><button type="button" class="light" onclick="closeModal()">Cancel</button><button class="primary">Save</button></div></form>',async function(f){await api('/api/appointments',{method:'POST',body:JSON.stringify(formData(f))});toast('Appointment saved');appointmentsPage()})}
async function delAppointment(id){if(confirm('Delete appointment?')){await api('/api/appointments/'+id,{method:'DELETE'});toast('Appointment deleted');appointmentsPage()}}
async function recordsPage(){var r=(await api('/api/medical-records')).data;patients=(await api('/api/patients')).data;var rows=r.map(function(x){return '<tr><td>'+x.recordDate+'</td><td>'+esc(x.patientName)+'</td><td>'+esc(x.diagnosis)+'</td><td>'+esc(x.treatment)+'</td><td>'+esc(x.notes)+'</td><td>'+(me.role==='Administrator'?'<button class="danger" onclick="delRecord('+x.id+')">Delete</button>':'')+'</td></tr>'}).join('');$('#main').innerHTML=shell('Medical Records','<button class="primary" onclick="recordModal()">+ Add Record</button>')+'<div class="panel"><table><thead><tr><th>Date</th><th>Patient</th><th>Diagnosis</th><th>Treatment</th><th>Notes</th><th>Action</th></tr></thead><tbody>'+(rows||'<tr><td colspan="6" class="empty">No medical records found.</td></tr>')+'</tbody></table></div>'}
function recordModal(){modal('Add Medical Record','<form><div class="grid"><label>Patient<select name="patientId" required>'+patients.map(function(p){return '<option value="'+p.id+'">'+esc(p.firstName+' '+p.lastName)+'</option>'}).join('')+'</select></label><label>Date<input name="recordDate" type="date" required></label><label class="full">Diagnosis<input name="diagnosis" maxlength="500" required></label><label class="full">Treatment<textarea name="treatment" maxlength="500" required></textarea></label><label class="full">Notes<textarea name="notes" maxlength="500"></textarea></label></div><div class="modal-actions"><button type="button" class="light" onclick="closeModal()">Cancel</button><button class="primary">Save</button></div></form>',async function(f){await api('/api/medical-records',{method:'POST',body:JSON.stringify(formData(f))});toast('Medical record saved');recordsPage()})}
async function delRecord(id){if(confirm('Delete medical record?')){await api('/api/medical-records/'+id,{method:'DELETE'});toast('Record deleted');recordsPage()}}
async function servicesPage(){services=(await api('/api/services')).data;$('#main').innerHTML=shell('Health Services',me.role==='Administrator'?'<button class="primary" onclick="serviceModal()">+ Add Service</button>':'')+'<div class="cards">'+services.map(function(s){return '<div class="card"><h3>'+esc(s.name)+'</h3><p class="muted">'+esc(s.description)+'</p><span class="status">'+s.status+'</span>'+(me.role==='Administrator'?'<p><button class="danger" onclick="delService('+s.id+')">Delete</button></p>':'')+'</div>'}).join('')+'</div>'}
function serviceModal(){modal('Add Health Service','<form><label>Name<input name="name" maxlength="100" required></label><label>Description<textarea name="description" maxlength="500" required></textarea></label><label>Status<select name="status"><option>Active</option><option>Inactive</option></select></label><div class="modal-actions"><button type="button" class="light" onclick="closeModal()">Cancel</button><button class="primary">Save</button></div></form>',async function(f){await api('/api/services',{method:'POST',body:JSON.stringify(formData(f))});toast('Service saved');servicesPage()})}
async function delService(id){if(confirm('Delete service?')){await api('/api/services/'+id,{method:'DELETE'});toast('Service deleted');servicesPage()}}
async function usersPage(){var u=(await api('/api/users')).data;$('#main').innerHTML=shell('Users','<button class="primary" onclick="userModal()">+ Add User</button>')+'<div class="panel"><table><thead><tr><th>Username</th><th>Name</th><th>Role</th><th>Created</th><th>Action</th></tr></thead><tbody>'+u.map(function(x){return '<tr><td>'+esc(x.username)+'</td><td>'+esc(x.fullName)+'</td><td>'+x.role+'</td><td>'+String(x.created_at).slice(0,10)+'</td><td>'+(x.id===me.id?'Current account':'<button class="danger" onclick="delUser('+x.id+')">Delete</button>')+'</td></tr>'}).join('')+'</tbody></table></div>'}
function userModal(){modal('Create User','<form><div class="grid"><label>Username<input name="username" minlength="3" maxlength="50" required></label><label>Full name<input name="fullName" required></label><label>Password<input name="password" type="password" minlength="8" required></label><label>Role<select name="role"><option>Staff</option><option>Administrator</option></select></label></div><div class="modal-actions"><button type="button" class="light" onclick="closeModal()">Cancel</button><button class="primary">Create</button></div></form>',async function(f){await api('/api/users',{method:'POST',body:JSON.stringify(formData(f))});toast('User created');usersPage()})}
async function delUser(id){if(confirm('Delete user?')){await api('/api/users/'+id,{method:'DELETE'});toast('User deleted');usersPage()}}
async function load(p){document.querySelectorAll('nav button').forEach(function(b){b.classList.toggle('active',b.dataset.page===p)});try{if(p==='dashboard')await dashboard();if(p==='patients')await patientsPage();if(p==='appointments')await appointmentsPage();if(p==='records')await recordsPage();if(p==='services')await servicesPage();if(p==='users')await usersPage()}catch(e){toast(e.message,true)}}
document.querySelectorAll('nav button').forEach(function(b){b.onclick=function(){if(b.id==='usersNav'&&me.role!=='Administrator')return;load(b.dataset.page)}})
$('#loginForm').onsubmit=async function(e){e.preventDefault();try{me=(await api('/api/login',{method:'POST',body:JSON.stringify({username:$('#username').value,password:$('#password').value})})).data;$('#login').className='hidden';$('#app').className='';$('#who').textContent=me.fullName+' • '+me.role;$('#usersNav').className=me.role==='Administrator'?'':'hidden';load('dashboard')}catch(x){toast(x.message,true)}}
$('#logout').onclick=async function(e){e.preventDefault();var btn=$('#logout');if(btn.disabled)return;btn.disabled=true;try{await api('/api/logout',{method:'POST'});}finally{me=null;$('#app').className='hidden';$('#login').className='login';$('#password').value='';btn.disabled=false;$('#username').focus()}}
(async function(){try{me=(await api('/api/me')).data;$('#login').className='hidden';$('#app').className='';$('#who').textContent=me.fullName+' • '+me.role;$('#usersNav').className=me.role==='Administrator'?'':'hidden';load('dashboard')}catch(e){}})();